### ISSUE TITLE
How to upgrade/migrate to the new syncing-server-js from the “old” syncing-server?

### ISSUE THREAD

**Issue by BobWs** [standardnotes/syncing-server-js#70]
Hi,
I’m running the SN syncing-server https://github.com/standardnotes/syncing-server together with SN web and Filesafe. I have noticed that syncing-server is deprecated. 

I also noticed that the new syncing server is much more comprehensive than the previous version. Several components are now required to run the server.

So my question is what is the best method to migrate to the new server without data loss? I can't find any information on this. Your tutorial is purely based on a new installation, but there are many users who are already running SN and there is no information on that.

**Comment by JaspalSuri** [comment]
Hi @BobWs, ~~I'll create a ticket for exploring the possibility of providing documentation to perform a migration from the old syncing server setup to the new one.~~ 

For migrating data (other than your server's settings for things like disabling registration), you could export backups of the accounts from the apps that are connected your syncing server, and then import them into the accounts authenticated in the apps connected to the new syncing server setup.

**Comment by atmoio** [comment]
It would likely depend entirely on your previous database setup. You would just specify your existing DB in the env params of the new server config. Just be sure to back it up before upgrading in case anything goes wrong.

**Comment by BobWs** [comment]
So basically I can just keep using the existing database with the new server? 

Because to download the data from all users separately and then re-import it into a new database is not exactly efficient.

I will try to migrate to the new server keeping the current database and see what happens.

**Comment by karolsojko** [comment]
Related to: https://github.com/standardnotes/standalone/issues/9

@BobWs can you try our new docs https://docs.standardnotes.org/self-hosting/legacy-migration/ and see if that helps?

Also keep in mind for self-hosting purposes plese use the `standalone` repo. The `syncing-server-js` repo is for development purposes only.

**Comment by BobWs** [comment]
> Related to: [standardnotes/standalone#9](https://github.com/standardnotes/standalone/issues/9)
> 
> @BobWs can you try our new docs https://docs.standardnotes.org/self-hosting/legacy-migration/ and see if that helps?
> 
> Also keep in mind for self-hosting purposes plese use the `standalone` repo. The `syncing-server-js` repo is for development purposes only.

I could give it a try but I will have to do that on another docker machine so I don’t screwup my users data.
Will let you know if it was a successful migration
